config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:edit, :delete]
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :address
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    service = CreateUser.new(params[:user])

    @user = service.call
    if @user.errors.blank?
      redirect_to users_path
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleUserForm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h2>Users list</h2>
<ol>
  <% User.all.each do |user| %>
    <li><%= "User: #{user.name} | Email: #{user.email}" %></li>
  <% end %>
</ol>

<%= link_to 'Create new user', new_user_path %>

app/views/users/new.html.erb
<h2>
  Create user
</h2>
<form action="/users" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>

  <div>
    <label for="user[name]">Name</label>
    <input type="text" name="user[name]" />
  </div>
  <div>
    <label for="user[email]">Email</label>
    <input type="text" name="user[email]" />
  </div>
  <div>
    <label for="user[address][city]">City</label>
    <input type="text" name="user[address][city]" />
  </div>
  <div>
    <label for="user[address][street]">Street</label>
    <input type="text" name="user[address][street]" />
  </div>
  <div>
    <label for="user[address][street_number]">Street nr</label>
    <input type="text" name="user[address][street_number]" />
  </div>

  <input type="submit" />

  <ul>
    <% @user.errors.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
</form>

<%= link_to 'Users List', users_path %>